### PR TITLE
Add subject device detail

### PR DESCRIPTION
**Pull request by herkulano**

### CODE REVIEW

**Review by mpgxvii — DISMISSED** [review]

**Review by kerzmaximilian — COMMENTED** [review]
@herkulano @mpgxvii - the current implementation is modelled on `301_Study-Subjects-Device Detail` or `302_Study-Subjects-Device Detail`? I would advocate for 301, so hovering over the entire row, rather than the specific column. Thoughts?

**Comment by mpgxvii** [comment]
I agree, also, (in 301) additional data of the patient could be added to the tile in the future, so data there is not limited to device status.

**Comment by herkulano** [comment]
Cool, there's one detail though this panel opens on click and not on hover, since it opens a panel and we have to load the individual sensors data, so to go to the details is a 2-click process. Pressing once on the row to open the detail and then on the "OPEN SUBJECT DATA" button.

**Comment by kerzmaximilian** [comment]
What if the panel is open by default? Then we could show the patient information on hover and the patient view on click.

**Comment by herkulano** [comment]
Because we don't get all the data from the API, both subject details and the sensors data, it will be awkward to show a constant loading as the user moves the mouse up and down the table. 

Click/press/tap is more intentional and permanent, there's less of an immediate feedback expectation from users and the data persists on screen until the user clicks again.

**Comment by kerzmaximilian** [comment]
Didnt think of that. Okay, any arguments against the 2 click approach? I like @mpgxvii idea to use the panel as a means to display other data in the future, also.

**Comment by herkulano** [comment]
@kerzmaximilian the argument against is that it takes longer for a researcher to go to the subject data, but this can be run through researchers when it's implemented to validate, it's easy enough to change at a later time. 

Also really like @mpgxvii idea, which adds an argument for having the 2 clicks, since there's more information that needs "processing" by researchers! 👍

**Comment by herkulano** [comment]
@mpgxvii @kerzmaximilian made the changes, please review.

**Pull request merged**
